# Generated by Django 5.1.4 on 2025-02-08 13:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='avatars/'),
        ),
    ]
