# Generated by Django 5.1.4 on 2025-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_to',
        ),
    ]
