# Generated by Django 5.1.4 on 2025-02-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_is_meeting_active_room_meeting_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_meeting_active',
        ),
        migrations.RemoveField(
            model_name='room',
            name='meeting_start_time',
        ),
    ]
